volumes:
  pgdata:
    driver: local

services:
  postgres:
    image: postgres:16-alpine
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - ${DB_PORT}:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
  
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: ["/code/entrypoint.sh"]
    ports:
      - 8080:8080
    restart: unless-stopped
    volumes:
      - .:/code
    depends_on:
      - postgres