name: Deploy to EC2

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Deploy via SSH
        env:
          PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          HOSTNAME: ${{ secrets.SSH_HOST }}
          USER_NAME: ${{ secrets.USER_NAME }}
        run: |
          echo "$PRIVATE_KEY" > key.pem && chmod 600 key.pem
          ssh -o StrictHostKeyChecking=no -i key.pem ${USER_NAME}@${HOSTNAME} '
            cd /home/ubuntu/ || { echo "Directory not found"; exit 1; }
            git pull origin main || { echo "Git pull failed"; exit 1; }
            docker system prune -f || { echo "Docker prune failed"; exit; }
            docker compose up -d --build || { echo "Docker compose up failed"; exit 1; }
          '
