name: Deploy to EC2

on:
  push:
    branches: [ main ]

jobs:
  Deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Debug secrets
        run: |
          echo "HOSTNAME is set: ${HOSTNAME:-unset}"
          echo "USER_NAME is set: ${USER_NAME:-unset}"
          echo "PRIVATE_KEY length: ${#PRIVATE_KEY}"
        env:
          PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          HOSTNAME: ${{ secrets.SSH_HOST }}
          USER_NAME: ${{ secrets.USER_NAME }}

      - name: Test SSH connection
        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME} whoami || { echo "SSH connection failed"; exit 1; }
        env:
          PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          HOSTNAME: ${{ secrets.SSH_HOST }}
          USER_NAME: ${{ secrets.USER_NAME }}

      - name: Deploy via SSH
        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME} '
            cd /home/ubuntu/ || { echo "Directory not found"; exit 1; }
            git pull origin main || { echo "Git pull failed"; exit 1; }
            docker compose down || { echo "Docker compose down failed"; exit 1; }
            docker compose up -d --build || { echo "Docker compose up failed"; exit 1; }
          '
        env:
          PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          HOSTNAME: ${{ secrets.SSH_HOST }}
          USER_NAME: ${{ secrets.USER_NAME }}